language: android
android:
  components:
    - build-tools-22.0.1
    - android-22

before_script:
  - chmod +x gradlew

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew :xlog-android:build :xlog-android:test :xlog-android:findbugs
  - ./gradlew :xlog-android-idle:build :xlog-android-idle:findbugs
  - ./gradlew :xlog-runtime:check :xlog-base:check